### ISSUE TITLE
satellite-slave won't start using json specification of comets

### ISSUE THREAD

**Issue by cmilloy** [twosigma/satellite#60]
When trying to start a satellite-slave using the new json method for specifying comets I'm getting an unexpected stacktrace. Could you take a look and provide any insight into what's happening?

main clojure config file
`
(require 'satellite-slave.mesos.recipes)
(def mesos-work-dir "/some/path/to/mesos/work")

(def settings
  (-> "/some/path/to/comets.json"
      clojure.java.io/reader
      (cheshire/parse-stream true)
       ))
`

comets.json
`
{
  "satellites": [
    {"host": "fakehostname.fakedomain.fake"},
    {"host": "fakehostname.fakedomain.fake"},
    {"host": "fakehostname.fakedomain.fake"}
  ],
  "service": "mesos/slave/",
  "comets": [
    {"name": "satellite-slave.recipes/free-memory",
     "period": "60s",
     "params": {"threshold": 1024}},
    {"name": "satellite-slave.recipes/free-swap",
     "period": "60s",
     "params": {"threshold": 50}},
    {"name": "satellite-slave.recipes/percentage-used",
     "period": "60s",
     "params": {"threshold": 90, "path": "/tmp"}},
    {"name": "satellite-slave.recipes/percentage-used",
     "period": "60s",
     "params": {"threshold": 90, "path": "/var"}},
    {"name": "satellite-slave.recipes/percentage-used",
     "period": "60s",
     "params": {"threshold": 90, "path": "/some/path/to/work/dir"}},
    {"name": "satellite-slave.recipes/num-uninterruptable-processes",
     "period": "60s",
     "params": {"threshold": 10}},
    {"name": "satellite-slave.recipes/load-average",
     "period": "60s",
     "params": {"threshold": 128}}
  ]
}
`

Resultant stacktrace:
`
Exception in thread "async-dispatch-3" Exception in thread "async-dispatch-5" Exception in thread "async-dispatch-1" java.lang.IllegalArgumentException: No implementation of method: :before? of protocol: #'clj-time.core/DateTimeProtocol found for class: nil
        at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:544)
        at clj_time.core$fn__115$G__56__122.invoke(core.clj:94)
        at chime$ms_between.invoke(chime.clj:8)
        at chime$chime_ch$fn__6231$state_machine__4346__auto____6232$fn__6234.invoke(chime.clj:41)
        at chime$chime_ch$fn__6231$state_machine__4346__auto____6232.invoke(chime.clj:37)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:940)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:944)
        at chime$chime_ch$fn__6231.invoke(chime.clj:37)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread "async-dispatch-7" java.lang.IllegalArgumentException: No implementation of method: :before? of protocol: #'clj-time.core/DateTimeProtocol found for class: nil
        at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:544)
        at clj_time.core$fn__115$G__56__122.invoke(core.clj:94)
        at chime$ms_between.invoke(chime.clj:8)
        at chime$chime_ch$fn__6231$state_machine__4346__auto____6232$fn__6234.invoke(chime.clj:41)
        at chime$chime_ch$fn__6231$state_machine__4346__auto____6232.invoke(chime.clj:37)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:940)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:944)
        at chime$chime_ch$fn__6231.invoke(chime.clj:37)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: No implementation of method: :before? of protocol: #'clj-time.core/DateTimeProtocol found for class: nil
        at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:544)
        at clj_time.core$fn__115$G__56__122.invoke(core.clj:94)
        at chime$ms_between.invoke(chime.clj:8)
        at chime$chime_ch$fn__6231$state_machine__4346__auto____6232$fn__6234.invoke(chime.clj:41)
        at chime$chime_ch$fn__6231$state_machine__4346__auto____6232.invoke(chime.clj:37)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:940)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:944)
        at chime$chime_ch$fn__6231.invoke(chime.clj:37)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread "async-dispatch-16" Exception in thread "async-dispatch-13" java.lang.IllegalArgumentException: No implementation of method: :before? of protocol: #'clj-time.core/DateTimeProtocol found for class: nil
        at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:544)
        at clj_time.core$fn__115$G__56__122.invoke(core.clj:94)
        at chime$ms_between.invoke(chime.clj:8)
        at chime$chime_ch$fn__6231$state_machine__4346__auto____6232$fn__6234.invoke(chime.clj:41)
        at chime$chime_ch$fn__6231$state_machine__4346__auto____6232.invoke(chime.clj:37)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:940)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:944)
        at chime$chime_ch$fn__6231.invoke(chime.clj:37)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread "async-dispatch-19" java.lang.IllegalArgumentException: No implementation of method: :before? of protocol: #'clj-time.core/DateTimeProtocol found for class: nil
        at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:544)
        at clj_time.core$fn__115$G__56__122.invoke(core.clj:94)
        at chime$ms_between.invoke(chime.clj:8)
        at chime$chime_ch$fn__6231$state_machine__4346__auto____6232$fn__6234.invoke(chime.clj:41)
        at chime$chime_ch$fn__6231$state_machine__4346__auto____6232.invoke(chime.clj:37)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:940)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:944)
        at chime$chime_ch$fn__6231.invoke(chime.clj:37)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: No implementation of method: :before? of protocol: #'clj-time.core/DateTimeProtocol found for class: nil
        at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:544)
        at clj_time.core$fn__115$G__56__122.invoke(core.clj:94)
        at chime$ms_between.invoke(chime.clj:8)
        at chime$chime_ch$fn__6231$state_machine__4346__auto____6232$fn__6234.invoke(chime.clj:41)
        at chime$chime_ch$fn__6231$state_machine__4346__auto____6232.invoke(chime.clj:37)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:940)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:944)
        at chime$chime_ch$fn__6231.invoke(chime.clj:37)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: No implementation of method: :before? of protocol: #'clj-time.core/DateTimeProtocol found for class: nil
        at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:544)
        at clj_time.core$fn__115$G__56__122.invoke(core.clj:94)
        at chime$ms_between.invoke(chime.clj:8)
        at chime$chime_ch$fn__6231$state_machine__4346__auto____6232$fn__6234.invoke(chime.clj:41)
        at chime$chime_ch$fn__6231$state_machine__4346__auto____6232.invoke(chime.clj:37)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:940)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:944)
        at chime$chime_ch$fn__6231.invoke(chime.clj:37)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
`

**Comment by mforsyth** [comment]
Hi @cmilloy, the problem here appears to be that the main clojure config file is missing "enrich-settings" (compare to the sample.clj in the repo).  So, among other things, the strings like "60s" aren't getting converted into actual time period objects.

This error message is "not the best"; perhaps we should put in some explicit validation for the format of the config :)

**Comment by cmilloy** [comment]
Even with this config.clj I get a long stacktrace. What I am going for is the simplest configuration which will let me run only json rules, not clojure rules. I'm not sure I even want a custom-comets method which may obviate the need for enrich-settings. Is there a way for me to specify the monitoring period (60s) in the json file which will not require enrichment/translation?

(require 'satellite-slave.mesos.recipes)
(def mesos-work-dir "some/path/to/mesos/work")

(def custom-comets
  [{:command ["echo" "17"]
    :schedule (every (-> 60 t/seconds))
    :output (fn [{:keys [out err exit]}]
              (let [v (-> out
                          (clojure.string/split #"\s+")
                          first
                          (Integer/parseInt))]
                [{:state "ok"
                  :metric v
                  :ttl 300
                  :description "example test -- number of files/dirs in cwd"}]))}])

(defn enrich-settings
  [s]
  (assoc s :comets (into custom-comets (map build-comet (:comets s)))))

(def settings
  (-> "some/path/to/mesos-slave-rules.json"
      clojure.java.io/reader
      (cheshire/parse-stream true)
       ))

**Comment by mforsyth** [comment]
@cmilloy  It is unavoidable that the values in the JSON file will require enrichment, because, for example, "60s" is not actually a sequence of joda times (which is what Satellite has always used in order to figure out when to send each event).  So "enriching" is the name we gave to the process of reading a simplified collection of static values like "60s" and converting it to the actual data structure of a Satellite comet.

The simplest way to avoid having any custom comets would be to start from the sample.clj file in the repo, and remove the example entry from the "custom-comets" vector... that way, if you ever DO need to add a comet to check a condition that's not one of the conditions that are already in the main Satellite repo, you don't have to change anything else, just add it to the vector at that point.

So, just replace the declaration of "custom-comets" with this:
(def custom-comets [])
.. and keep the function "enrich-settings"  and the declaration of the settings var the same as it is  in the sample.clj
.

**Comment by cmilloy** [comment]
Gotcha. This worked, thanks!
